<? 
	$this->placeholder('content_title')->set("Overzicht uitval per dag voor ".$this->date);
	$this->placeholder('autorefresh')->set("60");
?>

<?= $this->form; ?> 
<div class="break"></div>
<br /><br />
<hr />
<?= $this->Action('category','index','uitval',array('datum'=>$this->date)); ?>
<hr />
<?= $this->Action('bak','index','uitval',array('datum'=>$this->date)); ?>
<hr />
<?= $this->Action('dienst','index','uitval',array('datum'=>$this->date)); ?>
<hr />