<? 
	$this->placeholder('content_title')->set("Overzicht registraties per dag voor ".$this->date);
	$this->placeholder('autorefresh')->set("60");
?>

<?= $this->TableFilterform($this->tableHelper,"frm_period_and_state"); ?>
<?= $this->TableNumItemsform($this->tableHelper,"frm_itemsperpage","Toon:","&nbsp;items per pagina"); ?>
<?= $this->form; ?>
	        
<div class="clear"></div>
<?= $this->TablePagination($this->tableHelper,'pagination/pagination.phtml','Sliding'); ?>

<hr />

<table id="index" class="default fullwidth clickablerows">
	<?= $this->TableHeader($this->tableHelper); ?>
	<?= $this->TableBody($this->tableHelper); ?>
</table>
