<div id="result" label="<?= $this->label; ?>">

	<? if (isset($this->file_name)): ?>
		<div class="form_dd_col">
			<a target="blank" href="<?= $this->file_url; ?>">
				<img class="sample_pic" src="<?= $this->file_name; ?>" alt="<?= $this->file_title; ?>" />
			</a>					
		</div>				
	<? endif; ?>

	<?= $this->form; ?>
</div>

<? if (isset($this->file_name)): ?>
	<script type="text/javascript">
		$(document).ready(function(){
			$('.form_dd_col').insertBefore('.adminform #<?= $this->fieldname; ?>');
			$('#<?= $this->fieldname; ?>').wrap('<div class="form_dd_col" />');

			<? if (isset($this->file_delete)): ?>
				$('<br /><a class="img_delete_link" href="<?= $this->file_delete; ?>">verwijderen</a>').insertAfter('.adminform #<?= $this->fieldname; ?>');
			<? endif; ?>
			
			$('.adminform #<?= $this->fieldname; ?>').css('float','left');
		});
	</script>
<? endif; ?>