<p>Bij deze sturen wij u een herinnering voor de factuur met factuurnummer <b>%factuur_volgnummer%</b>.</p>
<p>
Mogelijk is de betaling van deze factuur aan uw aandacht ontsnapt. Wij verzoeken u het totaal bedrag deze factuur 
per omgaande over te maken op bankrekening 32.52.41.554 t.n.v. Remy Ameling.com
</p>

<b>Dit is een automatisch vezonden bericht.</b>

<p>Met vriendelijke groet,</p>

<p>
Remy Ameling<br />
Freelance Webdesigner<br /><br />

i.  www.remyameling.com<br />
m. info@remyameling.com<br />
t.  +31 06-29551798<br />
</p>