<p><a href="/admin/<?= $this->controller; ?>">Terug naar overzicht</a></p>

<h1>Bevestig verwijderen <?=$this->domain_displayname ?></h1>

<p>

<a class="abutton" href="<?= $this->url( array('controller'=>$this->ctrl,
							   'action'=>'index'),null,false); ?>">Annuleren</a>
<a class="abutton" href="<?= $this->url( array('controller'=>$this->ctrl,
							   'action'=>'delete',
							   'id'=>$this->id,
							   'confirm'=>'true')); ?>">Bevestigen</a>
</p>

<div class="clear">&nbsp;</div>							   