<div id="index" class="<?= $this->controller ?>">

<? echo $this->partial('components/tablemenu.phtml',	array('actions'=>$this->tableactions,
															  'currentaction'=>'index')); ?>

<h1>Sorteren <?=$this->domain_displayname ?>(s) (aantal : <?= $this->paginator->getTotalItemCount(); ?>)</h1>

<? echo $this->partial('components/filterform.phtml',array('controller'=>$this->controller,
														   'filtervalues'=>$this->filtervalues,
														   'action'=>$this->index,'params'=>array())); ?>
														   
<form class="smallform right" action="/admin/<?= $this->controller; ?>/savesort" method="post">
	<input type="submit" name="save_sort" id="save_sort" value="sortering opslaan" disabled="disabled" />
	<input type="hidden" name="save_sort_val" id="save_sort_val" value="0" />
	<input type="hidden" name="ff"   id="ff"   value="<?= $this->ff; ?>" />
	<input type="hidden" name="fv"   id="fv"   value="<?= $this->fv; ?>" />
	<input type="hidden" name="page" id="page" value="<?= $this->page; ?>" />
</form>											

<form id="frmindex" action="<?= $this->url( array('controller'=>$this->controller,'action'=>'dobulk')); ?>" method="post">

<table id="sort" class="sortable_table index alternate" cellspacing="0">

	

    <?= $this->partial('components/adminsortheader.phtml',	array('num_cols'=>$this->num_cols,
    																  'cols'=>$this->cols,
    																  'sorts'=>$this->sorts,
    																  'controller'=>$this->controller,
    																  'associations'=>$this->associations,    																  
  																	  'cursort'=>$this->sort,
    																  'curorder'=>$this->order,
    																  'sortableitems'=>$this->sortableitems)); ?>
    <?= $this->partial('components/adminsortbody.phtml',	array('paginator'=>$this->paginator,
    																  'cols'=>$this->cols,
    																  'decoder'=>$this->decoder,
    																  'entry'=>$this->entry,
    																  'controller'=>$this->controller,
    																  'associations'=>$this->associations,
    																  'sortableitems'=>$this->sortableitems,
    																  'pag'=>$this->paginator,
    																  'rowactions'=>$this->rowactions,
    																  'first_item_id'=>$this->first_item_id,
    																  'last_item_id'=>$this->last_item_id,
    																  'ff'=>$this->ff,
    																  'fv'=>$this->fv)); ?>
        
</table>




<? if (count($this->bulk_actions) > 0): ?>

<div id="bulk">
<label for="bulk_actions">Bulk aktie:</label>
<select id="bulk_actions" name="bulkaction">
	<? foreach($this->bulk_actions as $action): ?>
	<option><?= $action; ?></option>
	<? endforeach; ?>
</select>
<input type="submit" id="submitsort" value="uitvoeren"></input>
</div>
<? endif; ?>


</form>

<div id="pagination">
	<?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
	<?= $this->partial('components/countselector.phtml',	
					   array('controller'=>$this->controller,'ic'=>$this->ic)); ?>
</div>				   






</div>

