<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" />
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?= $this->partial('components/head.phtml',array()); ?>

<?  	
    echo $this->HeadScript();	
	echo $this->loadSkin("admin");
	echo $this->HeadLink();	
?>

</head>  

<body onload="initAdmin()">
	<div>
		<?php echo $this->layout()->content ?>
	</div>
</body>
</html>
