<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Administrator</title>

<script type="text/javascript" src="/js/jquery/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/js/jqueryui/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" src="/js/components/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/components/tables/tables.js"></script>
<script type="text/javascript" src="/js/components/tablednd/jquery.tablednd_0_5.js"></script>
<script type="text/javascript" src="/js/components/multilevel/filter.js"></script>
<script type="text/javascript" src="/js/components/autocopy/autocopy.js"></script>
<script type="text/javascript" src="/js/admin/ckeconfig.js"></script>
<script type="text/javascript" src="/js/admin/init.js"></script>
<script type="text/javascript" src="/js/admin/options.js"></script>
<script type="text/javascript" src="/js/components/dropdownmenu/dropdown.js"></script>

<link type="text/css" href="/js/jqueryui/css/ui-lightness/jquery-ui-1.8.10.custom.css" rel="stylesheet">