<div id="index" class="<?= $this->controller ?>">

	<? echo $this->partial('components/tablemenu.phtml',array('actions'=>$this->tableactions,
															  'currentaction'=>'edit',
															  'controller'=>$this->controller,
															  'previous_id'=>$this->previous_id,
															  'next_id'=>$this->next_id)); ?>
	
	<h1>Wijzigen product</h1>
	
	<?= $this->navigation()->menu()->setUlClass('tabs')->render($this->tabs); ?>
	
	<div class="content">	
		<? if (isset($this->file_name)): ?>
			<div class="form_dd_col">
				<a target="blank" href="<?= $this->file_url; ?>">
					<img class="sample_pic" src="<?= $this->file_name; ?>" alt="<?= $this->file_title; ?>" />
				</a>					
			</div>				
		<? endif; ?>
        
        <script>
			$(function() {
				$( "#tabs" ).tabs({ selected: <?= $this->tabidx; ?> });
			});
		</script>
		
		
		<div id="tabs">
			<ul>
				<li><a href="#productformulier">Product</a></li>
				<li><a href="#leverancierstabel">Leveranciers</a></li>
			</ul>
			
			<div id="productformulier">
				<?= $this->form; ?>
			</div>
			
			<div id="leverancierstabel">
			
				<a href="/admin/leverancierproduct/add/product_id/<?= $this->id; ?>">Leverancier toevoegen</a>
			
				<table id="test" class="index">
					<thead>
						<tr>
							<th>Naam</th>
							<th>Artikelnummer</th>
							<th>Prijs oms</th>
							<th>Prijs</th>
							<th>Min afname</th>
							<th>Akties</th>
						</tr>
					</thead>							
					<tbody>
						<? foreach($this->leveranciers as $leverancier): ?>						
							<tr>
								<td><?= $leverancier['leverancier_naam'] ?></td>
								<td><?= $leverancier['leverancierproduct_artikelnummer'] ?></td>
								<td><?= $leverancier['leverancierproduct_prijsomschrijving'] ?></td>
								<td><?= $leverancier['leverancierproduct_prijs'] ?></td>
								<td><?= $leverancier['leverancierproduct_minimaleafname'] ?></td>
								<td>
									<a href="/admin/leverancierproduct/edit/id/<?= $leverancier['id']?>"><img title="bewerken" src="/img/admin/edit.png"></a>
									<a href="/admin/leverancierproduct/delete/id/<?= $leverancier['id'] ?>"><img title="verwijderen" src="/img/admin/delete.png"></a>
								</td>
							</tr>
						<? endforeach; ?>
					</tbody>
				</table>			
			</div>
            
			<div class="clear"></div>
		</div>
		
		<div class="clear">&nbsp;</div>
	</div>

</div>

<? if (isset($this->file_name)): ?>
	<script type="text/javascript">
		$(document).ready(function(){
			$('.form_dd_col').insertBefore('.adminform #<?= $this->fieldname; ?>');
			$('#<?= $this->fieldname; ?>').wrap('<div class="form_dd_col" />');

			<? if (isset($this->file_delete)): ?>
				$('<br /><a class="img_delete_link" href="<?= $this->file_delete; ?>">verwijderen</a>').insertAfter('.adminform #<?= $this->fieldname; ?>');
			<? endif; ?>
			
			$('.adminform #<?= $this->fieldname; ?>').css('float','left');
		});
	</script>
<? endif; ?>